{{-- resources/views/posts/edit.blade.php --}}
<x-app-layout>
    <x-reddit-layout>
        <div class="space-y-6">
            <!-- Edit Post Header -->
            <div class="reddit-card">
                <div class="p-6">
                    <div class="flex items-center justify-between mb-4">
                        <h1 class="text-2xl font-bold text-neutral-900">Edit Post</h1>
                        <a href="{{ route('posts.show', $post) }}"
                           class="inline-flex items-center px-3 py-2 text-sm font-medium text-neutral-600 hover:text-reddit-orange transition-colors">
                            <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m0 7h18"/>
                            </svg>
                            Back to Post
                        </a>
                    </div>

                    @if($post->is_ai_generated)
                        <div class="mb-4 bg-purple-50 border border-purple-200 rounded-lg p-4">
                            <div class="flex items-center">
                                <svg class="w-5 h-5 text-purple-600 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/>
                                </svg>
                                <span class="text-sm text-purple-700 font-medium">This post was originally generated by AI</span>
                            </div>
                        </div>
                    @endif
                </div>
            </div>

            <!-- Edit Form -->
            <div class="reddit-card">
                <div class="p-6">
                    <form method="POST" action="{{ route('posts.update', $post) }}">
                        @csrf
                        @method('PATCH')

                        <div class="mb-6">
                            <label for="title" class="block text-sm font-medium text-neutral-700 mb-2">
                                Title
                            </label>
                            <input type="text" name="title" id="title"
                                   class="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-reddit-orange focus:border-reddit-orange"
                                   value="{{ old('title', $post->title) }}" required>
                            @error('title')
                                <p class="mt-2 text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="mb-6">
                            <label for="content" class="block text-sm font-medium text-neutral-700 mb-2">
                                Content
                            </label>
                            <textarea name="content" id="content" rows="12"
                                      class="w-full px-4 py-3 border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-reddit-orange focus:border-reddit-orange"
                                      placeholder="What's on your mind?"
                                      required>{{ old('content', $post->content) }}</textarea>
                            @error('content')
                                <p class="mt-2 text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="flex justify-between">
                            <a href="{{ route('posts.show', $post) }}"
                               class="inline-flex items-center px-6 py-3 text-sm font-medium text-neutral-600 bg-neutral-100 hover:bg-neutral-200 rounded-full transition-colors">
                                Cancel
                            </a>
                            <button type="submit"
                                    class="inline-flex items-center px-6 py-3 text-sm font-medium text-white bg-reddit-orange hover:bg-orange-600 rounded-full transition-colors">
                                Update Post
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </x-reddit-layout>
</x-app-layout>
